# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forbidigo
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 10
  
  dupl:
    threshold: 100
    
  funlen:
    lines: 100
    statements: 50
    
  gci:
    sections:
      - standard
      - default
      - prefix(htmlemail)
    custom-order: true
    
  gocognit:
    min-complexity: 10
    
  goconst:
    min-len: 2
    min-occurrences: 2
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
      
  gocyclo:
    min-complexity: 10
    
  goimports:
    local-prefixes: htmlemail
    
  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
      
  lll:
    line-length: 120
    
  misspell:
    locale: US
    
  nakedret:
    max-func-lines: 30
    
  nestif:
    min-complexity: 4
    
  nlreturn:
    block-size: 5
    
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
    
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
      - name: unhandled-error
        severity: warning
        
  stylecheck:
    checks: ["all"]
    
  unparam:
    check-exported: false
    
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - maintidx
        - wrapcheck
        
    # Exclude known linters from partially hard-to-fix issues
    - linters:
        - lll
      source: "^//go:generate "
      
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0